apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "main-service.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "main-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "main-service.name" . }}
    spec:
      containers:
        - name: main-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: EUREKA_SERVER_URL
              value: {{ .Values.env.EUREKA_SERVER_URL }}